// Colormaps generated by scripts/make_luts.py. batlow and grayC: Crameri, Scientific colour maps
// (10.5281/zenodo.1243862); viridis, cividis: matplotlib.
import * as THREE from 'three';
import luts from './luts.json';

export type LutName = keyof typeof luts;
export const LUT_NAMES = Object.keys(luts) as LutName[];

export function lutBytes(name: LutName): Uint8Array {
  const hex = luts[name];
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.substr(2 * i, 2), 16);
  return out;
}

export function lutTexture(name: LutName): THREE.DataTexture {
  const rgb = lutBytes(name), rgba = new Uint8Array(256 * 4);
  for (let i = 0; i < 256; i++) {
    rgba.set(rgb.subarray(3 * i, 3 * i + 3), 4 * i);
    rgba[4 * i + 3] = 255;
  }
  const t = new THREE.DataTexture(rgba, 256, 1, THREE.RGBAFormat, THREE.UnsignedByteType);
  t.magFilter = t.minFilter = THREE.LinearFilter;
  t.colorSpace = THREE.SRGBColorSpace;
  t.needsUpdate = true;
  return t;
}

/** CSS colour for t in [0, 1], for 2D views and the colorbar. */
export function lutColor(bytes: Uint8Array, t: number): string {
  const i = Math.max(0, Math.min(255, Math.round(t * 255))) * 3;
  return `rgb(${bytes[i]},${bytes[i + 1]},${bytes[i + 2]})`;
}
